### ISSUE TITLE
npm dev run后报错, 尝试改了版本号也不行,请教下要怎么解决

### ISSUE THREAD

**Issue by hejunv587** [KKslide/express-miniblog#12]
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack/bin/config-yargs'
Require stack:
- E:\website\express-miniblog-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\website\express-miniblog-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js:54:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\website\\express-miniblog-master\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1

**Comment by KKslide** [comment]
你用的是哪个分支呀?😂

**Comment by hejunv587** [comment]
> 你用的是哪个分支呀?😂

master,不应该用这个? 我看你这么说用了4.2.1,没有遇上这个问题.
