### ISSUE TITLE
\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\分之下,服务端会报错Cannot find module 'html'

### ISSUE THREAD

**Issue by hejunv587** [KKslide/express-miniblog#13]
Error: Cannot find module 'html'
Require stack:
- E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\view.js
- E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\application.js
- E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\express.js
- E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\index.js
- E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\app.js
- E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\bin\www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at new View (E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\view.js:81:14)
    at Function.render (E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\response.js:1008:7)
    at E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\app.js:98:9
    at Layer.handle_error (E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\router\index.js:315:13)
    at E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\router\index.js:335:12)
    at next (E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\router\index.js:315:13)
    at E:\website\express-miniblog-dependabot-npm_and_yarn-dot-prop-4.2.1\server\node_modules\express\lib\router\index.js:284:7

**Comment by hejunv587** [comment]
一系列找错后发现将app.js中改为如下所示, 后来可以直接打开,展示一个welcome.
// view engine setup
// app.set('views', path.join(__dirname, 'work'));
app.set('views', path.join(__dirname, 'views'));
// app.engine('html', ejs.__express);
// app.set('view engine', 'html');
app.set('view engine', 'jade');
是你在上传的过程中没有把新的work路径下的内容上传上来吗?

**Comment by KKslide** [comment]
工作在忙, 今晚先再回复你喔

**Comment by hejunv587** [comment]
> 工作在忙, 今晚先再回复你喔

非常感谢你. 我刚刚又仔细看了看代码,体会到了是我的理解错误. 但是app.set('views', path.join(__dirname, 'views'));app.set('view engine', 'jade'); 这个修改是必要的. 不然会报我提issue的错. 这会发现没有注册页面.
